# Generated by Django 3.2.4 on 2021-06-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0002_auto_20210619_0516'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrazilBills',
            new_name='BrazilsBills',
        ),
    ]
