# Generated by Django 3.2.4 on 2021-06-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0003_rename_brazilbills_brazilsbills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BrazilsBills',
            new_name='BrazilBill',
        ),
    ]
