# Generated by Django 3.2.4 on 2021-06-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0004_rename_brazilsbills_brazilbill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brazilbill',
            options={'verbose_name': 'My image', 'verbose_name_plural': 'My images'},
        ),
    ]
