# Generated by Django 3.2.4 on 2021-06-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0005_alter_brazilbill_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brazilbill',
            options={'verbose_name': "Brazil's Bill", 'verbose_name_plural': "Brazil's Bill"},
        ),
    ]
