# Generated by Django 3.2.4 on 2021-07-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_planning', '0015_nzshopping'),
    ]

    operations = [
        migrations.CreateModel(
            name='NZOffice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='item')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
            ],
            options={
                'verbose_name': "New Zealand's Office",
                'verbose_name_plural': "New Zealand's Office",
            },
        ),
    ]
